apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngopal-final-worker-deployment
  labels:
    app: ngopal-final-worker
    username: ngopal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngopal-final-worker
  template:
    metadata:
      labels:
        app: ngopal-final-worker
        username: ngopal
    spec:
      containers:
        - name: ngopal-final-worker
          imagePullPolicy: Always
          image: nrgopal/final:latest
          command: ['python', 'worker.py']
          #command: ['sleep', '999999']
          env:
          - name: WORKER_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: REDIS_IP
            value: 10.97.252.127
