apiVersion: v1
kind: Service
metadata:
  name: ngopal-final-redis-service
  labels:
    username: ngopal
    env: test
spec:
  type: ClusterIP
  selector:
    app: ngopal-final-redis
  ports:
  - name: ngopal-redis
    port: 6379
    targetPort: 6379
