---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-ngopal-final
  labels:
    username: ngopal
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi
