apiVersion: v1
kind: Service
metadata:
  name: ngopal-test-flask-service
  labels:
    username: ngopal
    env: test
spec:
  type: ClusterIP
  selector:
    app: ngopal-test-flask
  ports:
  - name: helloflask
    port: 5000
    targetPort: 5000
