apiVersion: v1
kind: Service
metadata:
  name: ngopal-test-redis-service
  labels:
    username: ngopal
    env: test
spec:
  type: ClusterIP
  selector:
    app: ngopal-test-redis
  ports:
  - name: helloredis
    port: 6379
    targetPort: 6379
