---
apiVersion: v1
kind: Pod
metadata:
  name: pod-b
  labels:
    version: "1.0"
    greeting: "personalized"
spec:
  containers:
    - name: pod-b
      image: ubuntu:18.04
      env:
        - name: NAME
          value: "Neel"
      command: ['sh', '-c', 'echo "Hello, $NAME!" && sleep 3600']
